### PR TITLE
add andromedaTemp folder to saveAndromeda

### LINKED ISSUE #58: saveAndromeda doesn't respect andromedaTempFolder
When `maintainConnection` is `TRUE` it makes a copy of the andromeda object when saving. This copy is not made into the andromedaTempFolder but rather the regular Rtmp folder. This is causing me issues on a system where I have a relatively small C drive for the operating system and a bigger one for the data and I'm extracting huge cohorts and specifying the `andromedaTemp` folder on the big drive.

I believe it should be very simple to fix. Add `tempdir= .getAndromedaTempFolder()` to all calls to `tempfile` in [saveAndromeda](https://github.com/OHDSI/Andromeda/blob/main/R/LoadingSaving.R#L54) function.

I'm happy to make a PR for this.

### PR DESCRIPTION
**Pull request by egillax**
Closes #58 

Verified these changes fixes my issue. Passes all tests locally.

### CODE REVIEW

**Comment by egillax** [comment]
@ablack3 I'm not sure what branch to make this PR to. Develop has all the arrow stuff while this is a bugfix unrelated to that.

**Comment by ablack3** [comment]
> @ablack3 I'm not sure what branch to make this PR to. Develop has all the arrow stuff while this is a bugfix unrelated to that.

Good point. You can make a new feature branch and target main if you like. I know that's not the standard hades approach but it's fine with me. I'll fix the develop brach next time I work on andromeda.

**Comment by egillax** [comment]
Hi @ablack3 ,

I changed it to now to target main. I as well updated the version to 0.6.4 and updated the news. 

I was getting an error in actions on macOS using the setup-r action. Same action was also complaining about being deprecated so I updated it's version and checked and updated versions of other actions used. 

Now the macOS check is failing for some other reason:

```
── Error ('test-object.R:204:3'): isAndromedaTable ─────────────────────────────
Error in `dyn.load(file, DLLpath = DLLpath, ...)`: bad value
Backtrace:
    ▆
 1. └─base::loadNamespace(x) at test-object.R:204:2
 2.   └─base::library.dynam(lib, package, package.lib)
 3.     └─base::dyn.load(file, DLLpath = DLLpath, ...)
 ```
 I'm not sure why this is happening? Any idea?

**Comment by egillax** [comment]
@ablack3  this is now ready for review. The reason it was failing previously on macOS was something to do with arrow v13. It's been fixed in arrow v14 which just came out.

**Pull request merged**
